language: go
go:
  - 1.11.x
services:
  - docker
git:
  submodules: false
install:
  - go get ./...
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=globbie/gnode
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "devel" ; fi`
  - echo $REPO:$TAG
  - docker build -f Dockerfile.build -t $REPO:$TAG.
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $REPO ; fi'
notifications:
  slack:
    secure: Wz69KlzHNuEJS45d3ybJJE892cDVInnRIPQa19ix0Tq8v1ke1hVg3/EPV82Sgp/hLBxmhjeKk6sDnEqsE5ndOb2xA54usoCReO+hulEVOsUlNUkMehk3HgfynQPATf3PVpgJPpbhl/V9v9zeK3cneBJagzGrbxFr9fM0lktsM9Jq6CmpkWkqVoU69XzjI36aGKdN8lAzEUMvMVrkx2FdN6nBHytWKugx5gEJG0IAMIv9FhhVf/nZvAePfuRbWzVdZh77h2PY/PTMpOBmK6jLSEM7BAcwQkT6r4bJT8WiEfANNT/xIz4+aZbjpbimj6hpq9P7HaeIxrMLTNI8ZXGgoMADRAnWfaFLa/ISdNR/MmUVWXLuCSZRCJ0Yd3dKRm4doeG+PUZDcSW8TG4e8aN1xHweO/1KpJljFamBvmMVLmQRh8GPksMWAd2dLROxlkvZeKPkVheFys4o533e0MptSLlowI2g7whrFzYo3OVK9LeiryuTv+7t1K9Jrab60gD98ut1rkVZhvrwsR7ZoZNLVdpJRcF9T3nP1O3/4uOmyYFQnt+nsTbc7f/fuigZ0N5wLgOydwVrTV95r74P2nIjNEK28a3AChHcY4VImNOTsIyvqhfjjLiY74aRCJu2ZoGHf1znBwTqgmxb3ArHTHdzuxqYfP1MGsrr+l6/teECSYU=
