sudo: required
language: go
go:
- 1.10.x
services:
- docker
git:
  submodules: false
install: true
script:
- docker build -t tmp -f Dockerfile.build .
notifications:
  slack:
    secure: Wz69KlzHNuEJS45d3ybJJE892cDVInnRIPQa19ix0Tq8v1ke1hVg3/EPV82Sgp/hLBxmhjeKk6sDnEqsE5ndOb2xA54usoCReO+hulEVOsUlNUkMehk3HgfynQPATf3PVpgJPpbhl/V9v9zeK3cneBJagzGrbxFr9fM0lktsM9Jq6CmpkWkqVoU69XzjI36aGKdN8lAzEUMvMVrkx2FdN6nBHytWKugx5gEJG0IAMIv9FhhVf/nZvAePfuRbWzVdZh77h2PY/PTMpOBmK6jLSEM7BAcwQkT6r4bJT8WiEfANNT/xIz4+aZbjpbimj6hpq9P7HaeIxrMLTNI8ZXGgoMADRAnWfaFLa/ISdNR/MmUVWXLuCSZRCJ0Yd3dKRm4doeG+PUZDcSW8TG4e8aN1xHweO/1KpJljFamBvmMVLmQRh8GPksMWAd2dLROxlkvZeKPkVheFys4o533e0MptSLlowI2g7whrFzYo3OVK9LeiryuTv+7t1K9Jrab60gD98ut1rkVZhvrwsR7ZoZNLVdpJRcF9T3nP1O3/4uOmyYFQnt+nsTbc7f/fuigZ0N5wLgOydwVrTV95r74P2nIjNEK28a3AChHcY4VImNOTsIyvqhfjjLiY74aRCJu2ZoGHf1znBwTqgmxb3ArHTHdzuxqYfP1MGsrr+l6/teECSYU=
