language: go

go:
- 1.11.x

services:
- docker

git:
  submodules: false

branches:
  except:
    - /^*-v[0-9]/

install:
- go get github.com/mattn/goveralls

script:
- export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`

- ./deploy.sh

- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN"

#- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push globbie/gnode ; fi

before_deploy:
- git config --local user.name "travis-ci"
- git config --local user.email "info@globbie.com"

- export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- git tag $TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#- git push -q --tags

- export TAG=$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
- echo $TAG

#- tar -czf gnode-linux-amd64.tar.gz gnode

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: coLeIchgfSlooA59eGyqLV27c+L+26yTOmAnvoEiH56yCtrCWHHNheMksJ8VWPr4z4lGBbPdSU+IrDTnid4LneeHq7BaCZANIQIxno98otbqIerH0q8VvEg1c82D1n7K51ezwJ5q7i+xqVMeJDLhXP3K1WvJnxNGzfU/apM7qeK32GT9pduon0NxJBIQBNJ/ovhgtmf/ywkqnAnutmQvhoRGL89uwarQWu+pGNkOnSp5l+c9WN3XHOSYGgOC7ifqe821Ny7tekeolXKpWKn85cV+Ca8xKC0A3QyFDuGpZS7HzBOLzyJSrrWNo8dV4VebLGQO+VHZswO+1iha5WtndZDWOUyupt/ERfNt6KOzsPEBsN7yA6zqfldfTYIb4mKk4rAETX0OoKvPgFk/pfP8CNQnAwOGxUscLVSZwAqap0NZxoyRFDzxT4/Kug73c2geKLnHHejtpkvglEeqsjHNd4vJeTksZX8VvcWbtKHgxhRNndNxM/BfiLQmxhF6qp6MJ9jdMjyGob6jN/9qpDFBpndrOYMIHt/pQS3ZeuuwEdgg3xEfseDmHlgJ8BApZwq7gecADNJ7XuIYDyYFIf5Nf9m7fvdLsUX66wr9hE0bOABxYD/72sj8eN2UZv3RZE6J0/Px0K+p0aok6nGu0YKF8/9CCfN6bvgFWqppFiSRn6U=
  file: README.md
  on:
    tags: false
    repo: globbie/gnode
    branch: master

notifications:
  slack:
    secure: Wz69KlzHNuEJS45d3ybJJE892cDVInnRIPQa19ix0Tq8v1ke1hVg3/EPV82Sgp/hLBxmhjeKk6sDnEqsE5ndOb2xA54usoCReO+hulEVOsUlNUkMehk3HgfynQPATf3PVpgJPpbhl/V9v9zeK3cneBJagzGrbxFr9fM0lktsM9Jq6CmpkWkqVoU69XzjI36aGKdN8lAzEUMvMVrkx2FdN6nBHytWKugx5gEJG0IAMIv9FhhVf/nZvAePfuRbWzVdZh77h2PY/PTMpOBmK6jLSEM7BAcwQkT6r4bJT8WiEfANNT/xIz4+aZbjpbimj6hpq9P7HaeIxrMLTNI8ZXGgoMADRAnWfaFLa/ISdNR/MmUVWXLuCSZRCJ0Yd3dKRm4doeG+PUZDcSW8TG4e8aN1xHweO/1KpJljFamBvmMVLmQRh8GPksMWAd2dLROxlkvZeKPkVheFys4o533e0MptSLlowI2g7whrFzYo3OVK9LeiryuTv+7t1K9Jrab60gD98ut1rkVZhvrwsR7ZoZNLVdpJRcF9T3nP1O3/4uOmyYFQnt+nsTbc7f/fuigZ0N5wLgOydwVrTV95r74P2nIjNEK28a3AChHcY4VImNOTsIyvqhfjjLiY74aRCJu2ZoGHf1znBwTqgmxb3ArHTHdzuxqYfP1MGsrr+l6/teECSYU=
