sudo: required

language: go

go:
    - "1.10.x"

git:
    submodules: false

# manual handle git submodules
before_install:
    - find . -name ".gitmodules" | xargs sed -i 's/git@github.com:/https:\/\/github.com\//'
    - find . -name ".gitmodules" | xargs cat
    - git submodule update --init
    - find . -name ".gitmodules" | xargs sed -i 's/git@github.com:/https:\/\/github.com\//'
    - find . -name ".gitmodules" | xargs cat
    - git submodule update --init --recursive

script:
    - go test -v ./...
